[tool.poetry]
name = "msys2-devtools"
version = "0.1.0"
description = ""
authors = ["Christoph Reiter <reiter.christoph@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
netaddr = "^0.8.0"
tabulate = "^0.9.0"
requests = "^2.28.2"
zstandard = "^0.19.0"

[tool.poetry.scripts]
msys2-srcinfo-cache = 'msys2_devtools.srcinfo_cache:run'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
